name: Deploy SWA Counter API

on:
  push:
    branches:
      - main
    paths:
      - "azure/swa-counter-api/**"
      - ".github/workflows/deploy-swa-counter-api.yml"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_COUNTER_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"

          app_location: "azure/swa-counter-api/app"
          api_location: "azure/swa-counter-api/api"
          output_location: ""
